version: "3"

volumes:
  dbdata:

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: "postgres_container"
    ports:
      - "54321:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: blog
